server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yunfei
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: microservice-provider-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true